Update execution.yml

diff --git a/.github/workflows/execution.yml b/.github/workflows/execution.yml
--- a/.github/workflows/execution.yml
+++ b/.github/workflows/execution.yml
@@ -30,14 +30,17 @@ jobs:
       - name: Update PATH
         run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
 
-      - name: List global tools
-        run: dotnet tool list --global
+        #- name: List global tools
+        #run: dotnet tool list --global
 
-      - name: Build the project  # Add this step
+      - name: Build the project
         run: dotnet build TechnicalTaskWithPlaywright.sln
+
+        #- name: List Playwright Cache
+        #run: ls -R $HOME/.cache/ms-playwright
         
       - name: Install Playwright Browsers
-        run: playwright install
+        run: playwright install || (echo "Failed to install Playwright browsers" && exit 1)
 
   test:
     runs-on: ubuntu-latest
@@ -66,17 +69,21 @@ jobs:
       - name: Update PATH
         run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
 
-      - name: List global tools
-        run: dotnet tool list --global
+        #- name: List global tools
+        #run: dotnet tool list --global
 
-      - name: Build the project  # Add this step
+      - name: Build the project
         run: dotnet build TechnicalTaskWithPlaywright.sln
 
+        #- name: List Playwright Cache
+        #run: ls -R $HOME/.cache/ms-playwright
+        
       - name: Install Playwright Browsers
-        run: playwright install
+        run: playwright install || (echo "Failed to install Playwright browsers" && exit 1)
 
       - name: Run tests
-        run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --logger "console;verbosity=detailed"
+        run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --filter "FullyQualifiedName~${{ matrix.test }}"
+        #run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --logger "console;verbosity=detailed"
 
       - name: Install Allure CLI
         run: |
