Update execution.yml

diff --git a/.github/workflows/execution.yml b/.github/workflows/execution.yml
--- a/.github/workflows/execution.yml
+++ b/.github/workflows/execution.yml
@@ -39,11 +39,8 @@ jobs:
         #- name: List Playwright Cache
         #run: ls -R $HOME/.cache/ms-playwright
         
-        #- name: Install Playwright Browsers
-        #run: playwright install || (echo "Failed to install Playwright browsers" && exit 1)
-
-      - name: Install Playwright Browsers via PowerShell
-        run: pwsh -Command "& { ./bin/Debug/net8.0/playwright.ps1 install }" # Adjust path as necessary
+      - name: Install Playwright Browsers
+        run: playwright install || (echo "Failed to install Playwright browsers" && exit 1)
 
   test:
     runs-on: ubuntu-latest
@@ -67,7 +64,8 @@ jobs:
         run: dotnet restore TechnicalTaskWithPlaywright.sln
 
       - name: Run tests
-        run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --filter "FullyQualifiedName~${{ matrix.test }}"
+        #run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --filter "FullyQualifiedName~${{ matrix.test }}"
+        run: dotnet test Tests/Tests.csproj --configuration Release --verbosity normal --logger "console;verbosity=detailed"
 
       - name: Install Allure CLI
         run: |
